### ISSUE TITLE
Please add WildFly Preview as Jakarta EE 9 Full Platform compatible

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/jakarta.ee#1126]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**

https://www.eclipse.org/membership/showMember.php?member_id=731

**A product name and version**

[WildFly Preview 23.0.1.Final](https://wildfly.org/downloads)

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**

Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**

https://github.com/wildfly/certifications/blob/EE8/images/wildfly-logo-stacked-100px-2132977.zip?raw=true

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

Red Hat

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/326

**The URL where Compatible Software Product is available for download**

https://wildfly.org/downloads

**Comment by scottmarlow** [comment]
Could you please list product `WildFly Preview` under https://jakarta.ee/compatibility/#tab-9 instead of `WildFly` for both the Web Profile + Full Platform entries?

**Comment by TanjaObradovic** [comment]
Looks good to me

**Comment by linkfang** [comment]
Hi @TanjaObradovic , here is the preview link for the changes:
https://deploy-preview-1128--jakartaee.netlify.app/

**Comment by linkfang** [comment]
Hi @TanjaObradovic , I would like to confirm an issue the team found.

If we use WildFly Preview for the product name, then in Jakarta EE compatible products tab, we will see 2 WildFly in the list. One is WildFly and the other is WildFly Preview. Is this something we suppose to show?
Check here: https://deploy-preview-1128--jakartaee.netlify.app/compatibility/#tab-one 

If we would like to have just 1 WildFly in the Jakarta EE compatible products tab, then I suggest we put the "Preview" in the version instead of the product name. Like "23.0.1.Preview.Final". We have similar version format for "Open Liberty", its version number is "21.0.0.3-beta". We also have a stable version of "Open Liberty" in the Jakarta EE 8 tab. So, the situation is quite similar.
Check here: https://deploy-preview-1128--jakartaee.netlify.app/compatibility/#tab-9

What do you think?
Thanks!

**Comment by bstansberry** [comment]
@linkfang @TanjaObradovic 

WildFly Preview is a separate distribution from standard WildFly, so it's valid to have a separate entry on the Jakarta EE compatible products tab. It's not ideal (because it's kind of busy) but I think it's better than sticking the word preview in the version number.  I believe the 21.0.2-beta for OpenLiberty maps to an actual release version (see https://mvnrepository.com/artifact/io.openliberty.beta/openliberty-jakartaee9/21.0.0.2-beta)

If having two items on the compatible products page is unacceptable and spaces are ok in the version something like "Preview 23.0.2.Final" would be work.

**Comment by TanjaObradovic** [comment]
@bstansberry @linkfang I agree it is not ideal to have a separate entry for the preview, so having "Preview 23.0.1.Final" as a version is actually the way to go. We should follow what we already have with OpenLiberty.

**Comment by linkfang** [comment]
Here is the preview link:
https://deploy-preview-1128--jakartaee.netlify.app/

Let me know what do you think, thanks!

**Comment by TanjaObradovic** [comment]
As long as we have both versions listed for WildFly, 23.0.0 and Preview 23.0.1.Final that would be fine. If I am missing something please let me know. @bstansberry @scottmarlow  can you please confirm?

**Comment by bstansberry** [comment]
@linkfang @TanjaObradovic @scottmarlow https://deploy-preview-1128--jakartaee.netlify.app/ LGTM. Thanks.

**Comment by scottmarlow** [comment]
@TanjaObradovic @linkfang @bstansberry looks good to me also!  Thank you!

**Comment by TanjaObradovic** [comment]
great! thanks! looks good to me!
