### ISSUE TITLE
Newsletter archive refresh

### ISSUE THREAD

**Issue by autumnfound** [jakartaee/jakarta.ee#1151]
Newsletter archives is a simple facelift and rearranging of content to make use of the same look and feel that exists across the site refresh. The year header has a glyph to the left of it, and underneath the header is a simple list of links. Instead of being a full width section, these lists will be in smaller bordered boxes
 
@karenmcnaughton the presence of links is only assumed here as there is no indication that the text in these sections is linked. The best practice is to somehow decorate the text to indicate it isn't standard text to indicate the presence of a link. Either with different color text, an underline, or a glyph. 

The default would be to allow the standard treatment of links to apply, which would make the text a different color. Do you have a preference for some other look, or does this work for you?

Design:
https://projects.invisionapp.com/share/AX10M9QL74RN#/screens/448585128
![image](https://user-images.githubusercontent.com/23018241/117462325-8c234980-af1c-11eb-97d7-5ddbf283174a.png)

**Comment by ericpoirier** [comment]
@shabnammayel @excentrickristy @shanda-eclipse  I updated the Newsletter archive page on staging
https://deploy-preview-1304--jakartaee.netlify.app/community/newsletter/

Let me know if there's anything else.

Thanks.

**Comment by shanda-eclipse** [comment]
Layout looks fine, but there should be some 2021 content and I'm not sure where this fits in the menu structure. Might need to wait until @shabnammayel is back to finalize this.

**Comment by excentrickristy** [comment]
I looked back at the Site Architecture spreadsheet and it’s not accounted for in the interim nav, so we will need to wait for Shabnam on that one.

Despite its navigation location, I think a good spot to link to it would be to on the stay connected page in the newsletter section. There is a button for subscribe and you could add a button beside it that says “View Archives”

In terms of the layout, the original design had the icons and titles lining up, it would be nice if we could do that.

SEO wise the meta tags and headers are good!

**Comment by ericpoirier** [comment]
@shanda-eclipse @excentrickristy there is currently a link in the sidebar that goes to Newsletter Archive.

https://deploy-preview-1300--jakartaee.netlify.app/connect/

That being said, it wouldn't hurt to add a button in the Stay Connected page as well as a menu item but I wouldn't concider this a blocker to publish the redesign of the page.

@excentrickristy I decided to split the icon and the title on two line because this is what we are doing on the following page.

https://deploy-preview-1298--jakartaee.netlify.app/resources/

So to keep things consistant I thought i would be good to do that. But I can put it on one line if you think its preferable.

**Comment by excentrickristy** [comment]
@ericpoirier on the current live site, the new version of the stay connected page is published though and there is no sidebar. The sidebar only exists on a few pages under the about the jakarta ee working group menu. These will be replaced soon so in light of that, I think it would make sense to add a button on the stay connected page to access the archive page, especially because that's where it makes the most sense in context of the content.

In regard to the icons, I do prefer them them on the same line as the year, especially since they are all the same. Whereas in resources the icons have more visual meaning. It's just my personal preference though!

**Comment by ericpoirier** [comment]
> @ericpoirier on the current live site, the new version of the stay connected page is published though and there is no sidebar. The sidebar only exists on a few pages under the about the jakarta ee working group menu. These will be replaced soon so in light of that, I think it would make sense to add a button on the stay connected page to access the archive page, especially because that's where it makes the most sense in context of the content.
> 
> In regard to the icons, I do prefer them them on the same line as the year, especially since they are all the same. Whereas in resources the icons have more visual meaning. It's just my personal preference though!

I added the button on the Stay Connected page
https://deploy-preview-1304--jakartaee.netlify.app/connect/

I also updated the title layout so that its lined up:
https://deploy-preview-1304--jakartaee.netlify.app/community/newsletter/

Let me know if there's anything else.

Thanks.

**Comment by excentrickristy** [comment]
Beautiful, @ericpoirier!
