### ISSUE TITLE
Release landing page for version 9 needs to be corrected

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakarta.ee#1176]
![image](https://user-images.githubusercontent.com/40073121/118293995-429ca680-b4a8-11eb-8e5d-b761492b4c2c.png)

Per our chat yesterday, can we make sure we correct this?
Home  / Jakarta EE 8 Delivers  / Jakarta EE 9 Delivers

it should be 
Home / Jakarta EE 9 Delivers

**Comment by autumnfound** [comment]
@TanjaObradovic Please see https://deploy-preview-1185--jakartaee.netlify.app/release/9/ for a preview of the fix! The best we could easily do is update the title of the release page which was still technically Jakarta EE 8 Delivers, which is why it showed up strangely in the breadcrumb. It now reads Home > Jakarta EE Releases > Jakarta EE 9 Delivers, which is much more clear and preps us for a potential releases home page in the future!
