### ISSUE TITLE
Documentation for adding new entry in /news/ and Announcements section  is need it

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakarta.ee#1196]
Current https://github.com/jakartaee/jakarta.ee/README.md needs to provide the instruction on how to:
- Add documentation for creating a new entry in https://jakarta.ee/news/ #1195
- How to add a reference in Jakarta EE Announcements section from one Jakarta EE Working Group post

**Comment by cesarhernandezgt** [comment]
Hi @TanjaObradovic @karenmcnaughton 
The two above Pr's are related to website documentation. After technical review, it seems both PR's are waiting for your approval to be merged.

**Comment by aeiras** [comment]
@chrisguindon & @TanjaObradovic, 
Thank you and the team for helping us move forward to complete this task. We appreciate our collaboration with you! 

@cesarhernandezgt's work on anything related to the EE 9.1 page **ends** tomorrow. 
We hope that any issues with this particular task are raised before the invested time expires.  

Should any unknown issues push this ticket to next week, you are welcomed to add me, **instead of Cesar**.

**Comment by cesarhernandezgt** [comment]
Both Pr's were merged; thank you all for the collaboration.
Closing now is this GitHub issue.
