### ISSUE TITLE
Please add Apusic Application Server V9 as Jakarta EE 8 Full Platform compatible

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/jakarta.ee#1286]
To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

**The URL to the Eclipse Foundation profile to confirm that you are an authorized representative of the company whose product information you are submitting**
https://www.eclipse.org/membership/showMember.php?member_id=1397

**A product name and version**
AAS V9

**The Profile (Full Platform, Web Profile, Both) that the Compatible Product is submitted to be listed under**
Full Platform

**A ZIP file with a product logo with a transparent background in SVG format (optional)**
https://github.com/apusic/aas-tck/blob/master/aas.jpg

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**
Kingdee Apusic cloud computing Co., Ltd.

**The URL to the approved certification issue demonstrating compatibility as defined in the Jakarta EE TCK Process**
https://github.com/eclipse-ee4j/jakartaee-platform/issues/412

**The URL where Compatible Software Product is available for download**
https://www.apusic.com/list-117.html

**Comment by linkfang** [comment]
Hi @PatrickHuang888 ,

I found the download URL (the one associated to AAS logo) for AAS V10 on EE9.1 and EE9 doesn't work now.
When I click the AAS logo, it will lead me to a "Page doesn't exist" page, so I updated them with the new one you offered in this issue. (From "http://www.apusic.com/info_safety/server" to "https://www.apusic.com/list-117.html")

Does this work for you?

And for the Public URL of TCK Results Summary, the ones for V10-EE9.1 (platform) and V10-EE9 (both platform and web) don't work properly as well. I will also be led to a "Page doesn't exist" page.
Can you confirm if the URLs changed and if so, can you please give me the new ones so that I can update them accordingly?

Please preview here:
https://deploy-preview-1288--jakartaee.netlify.app/compatibility/#tab-9_1

Thanks!

**Comment by PatrickHuang888** [comment]
Hi @linkfang 
As I asked the IT guys, they have upgraded web site, so yes, tck results URL changed.
V10 ee8 tck results https://www.apusic.com/about/aas_v10_ee8.html  
V10-EE9 web ee9 tck results https://www.apusic.com/about/aas_v10_ee9_webtck.html
V10-EE9 full ee9 tck results https://www.apusic.com/about/aas_v10_ee9_full.html  
V10-EE9 ee9.1 tck results https://www.apusic.com/about/aas_v10_ee9-1_full.html  
and downloads URL all under https://www.apusic.com/list-117.html

Thanks
Patrick

**Comment by linkfang** [comment]
Cool!

Hi @PatrickHuang888 , @ivargrimstad , @TanjaObradovic ,
Please preview the changes here:
https://deploy-preview-1288--jakartaee.netlify.app/compatibility/#tab-8

**Comment by TanjaObradovic** [comment]
LGTM!
