### ISSUE TITLE
News Page vs Newsroom Canonical Links

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1346]
As per a conversation with @shabnammayel 

Because the same news post is being posted here:
https://jakarta.ee/news/2021-jakarta-ee-developer-survey/

As well as here:
https://newsroom.eclipse.org/news/announcements/eclipse-foundation-announces-results-2021-jakarta-ee-developer-survey

For the Jakarta EE News room posts to gain rank and help us increase search visibility the canonical link on the newsroom post should point back the original jakarta.ee post.

Is it possible to add an input field on newsroom posts to set the canonical link to something different?

![image](https://user-images.githubusercontent.com/73264129/144654414-447c81f0-12e0-4951-98c7-25c80ef7fd66.png)

**Comment by ericpoirier** [comment]
@chrisguindon If I look at the configs or the Metatags in newsroom.eclipse.org, the default conanical url is the "current-page:url". We could change the default by using hook_metatag_metatags_view_alter() and either use the value of field_news_url or we could create a new url field to deal with the conanical url only. 

I created a draft MR using the hook I'm mentioning:
https://gitlab.eclipse.org/eclipsefdn/it/webdev/drupal/eclipse_api/-/merge_requests/9

Let me know what you think.

**Comment by chrisguindon** [comment]
+1 I am fine with a solution that would allow us to alter the value of canonical URL using hook_metatag_metatags_view_alter() but only if the field_news_url is set and not empty since that's probably the default behavior that we want.

Please note that the marketing team can set a value for each news item. This functionally already exists in the newsroom.

You will need to make sure not to alter that value if a custom URL was added to the canonical URL of the news item.

![Capture](https://user-images.githubusercontent.com/893942/145891360-a85c4ff3-561d-4aab-8175-1cc3896a7b62.PNG)

**Comment by chrisguindon** [comment]
I would consider this an enhancement request since we already support the canonical URLs  in the newsroom.

**Comment by ericpoirier** [comment]
> I would consider this an enhancement request since we already support the canonical URLs in the newsroom.

Sounds good.

**Comment by chrisguindon** [comment]
@ericpoirier I see that your PR has been merged. Are we done here? If not what's left?

**Comment by ericpoirier** [comment]
I think we are done here.

@excentrickristy @shabnammayel please reopen if something is missing.

Thanks.
