### ISSUE TITLE
Replace "contributor" card on jakarta.ee/resources/community-cards/

### ISSUE THREAD

**Issue by jph152** [jakartaee/jakarta.ee#1356]
Please replace the [last card](https://jakarta.ee/resources/images/jakarta-ee-contributor-card.png) on this page with the following:

![Jakarta EE Community Cards - Large](https://user-images.githubusercontent.com/69642121/145599276-c0f26961-76de-4f84-b41c-731724f30ef7.png)

**Comment by linkfang** [comment]
Please preview the changes here:
https://deploy-preview-1359--jakartaee.netlify.app/resources/community-cards/

Please note, the image provided in this issue is a little smaller than other card images. (1200x629 VS 1800x942)
So, if we click the image to open it in the tab, it will look smaller than the other ones.

Do we need to make sure the sizes are consistent?

**Comment by jph152** [comment]
Let's use this version you view after clicking on the preview image. It should be the same size as the others

<img width="900" alt="Jakarta EE Community Cards - Large (1)" src="https://user-images.githubusercontent.com/69642121/145882485-75889562-0b5b-42b3-be68-ebaa4abbcf89.png">

**Comment by linkfang** [comment]
Cool!

Here is the updated version:
https://deploy-preview-1359--jakartaee.netlify.app/resources/community-cards/

**Comment by jph152** [comment]
+1
