### ISSUE TITLE
Add to the news section of the website

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1407]
Please add my write up to the News section of Jakarta EE's website here:https://jakarta.ee/news/

Here is the link to my article: https://docs.google.com/document/d/1Z-Z253uFdDKl5e4JQFr-Ka739OFedFEx2gRH32CBU3E/edit

Thanks

**Comment by linkfang** [comment]
Hi @shabnammayel , please preview the updates here:
https://deploy-preview-1410--jakartaee.netlify.app/news/
https://deploy-preview-1410--jakartaee.netlify.app/news/the-jakarta-ee-website-is-now-redesigned/

Please note, I changed the comma after thanks to an exclamation mark because the comma feels more like an email, let me know if this works for you.
![image](https://user-images.githubusercontent.com/43075439/154089463-ecc6f603-88a1-4df9-95ae-4206fd7ea350.png)

![image](https://user-images.githubusercontent.com/43075439/154089482-c6943bbe-9d32-45a5-850f-6b181be5ce2a.png)

**Comment by shabnammayel** [comment]
LGTM! Thanks

**Comment by linkfang** [comment]
NP! The change is now live!
