### ISSUE TITLE
Aesthetic/Usability Recommendation

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1445]
Recommending the following CSS to restrict the website size on larger screen sizes to 1920px. This will help improve the appearance of full width banners like the one at the bottom of the [release pages](https://jakarta.ee/release/9.1/) for those with larger screen sizes. This is just an aesthetic suggestion and open to feedback!

html {    
    width: 1920px;
    max-width: 100%;
    margin: 0 auto;
    background-color: #f7f7f7;
}

body {
    box-shadow: 1px 0px 6px 2px #88888861;
}

I've attached a screenshot of how this would appear on a 2560px screen. It won't affect the appearance for anyone 1920px or under.

![Screenshot 2022-03-24 100329](https://user-images.githubusercontent.com/73264129/159934049-0d175e6b-f042-4196-91c0-ed4a8ba70d73.png)

**Comment by linkfang** [comment]
Hi @excentrickristy , thanks for the suggestion! And I do agree that it's important to make the page look good on various screens.

I created a PR based on your comment so that we can see the result in action. 
https://deploy-preview-1448--jakartaee.netlify.app/

As you might noticed, on production site, the banner is allowed to occupy the full width of the window while the actual content (text content) is restricted to 1170px. 
This is a pretty common way to handle with large windows. Such as, [Adobe](https://www.adobe.com/ca/), [Apple](https://www.apple.com/ca/), [Microsoft](https://www.microsoft.com/en-ca/surface), [Red Hat](https://www.redhat.com/en), etc. are doing similar things. So, I personally don't think it's an issue as the content won't grow larger than 1170px so that user's attention will always be kept in the middle of the page.

With a 1920px restriction and the box shadow, there is obvious cut off on the page (left and right). So, I would suggest we stay with current solution. WDYT?

**Comment by excentrickristy** [comment]
The content itself is not as much an issue as full width banners like the one you see near the bottom of the release page with the whitepaper download: https://deploy-preview-1448--jakartaee.netlify.app/release/9.1/
At full width on bigger screen sizes this gets kind of crazy looking! There aren't many instances of this though, so I will defer to @shabnammayel

**Comment by linkfang** [comment]
Ah, OK, sorry I was not looking at the right section! 😂

Do you think it's a little too blur on larger screens? If so, I can add restrictions on the image to make sure it's no larger than 1920px and make the background a blur version of it. Similar to this,
![image](https://user-images.githubusercontent.com/43075439/160194083-ef7460a3-8677-46ae-8ec6-57f7a9d27cae.png)

Or if you think it's too tall then I can add restrictions to the height.

**Comment by ericpoirier** [comment]
@excentrickristy

**Comment by linkfang** [comment]
Here is the preview of the change I mentioned above:
https://deploy-preview-1448--jakartaee.netlify.app/release/9.1/

One of the reasons for this issue is that the image we use here is a png file with transparent background color. So, on a larger screen, to be able to make the image fill the width of that section, the height will be cut off (mainly the transparent parts), so the image will look higher.

Like this:
![image](https://user-images.githubusercontent.com/43075439/161588077-53b29990-0938-454a-abc6-356b3050f118.png)
 
When the screen/browser is narrower, the width will be cut off so the height will look the same. Like so:
![image](https://user-images.githubusercontent.com/43075439/161588476-9bbc5be0-4da3-4e80-a723-56429e72a8f3.png)

**Comment by excentrickristy** [comment]
Love the look of the blur! On my 2560px width screen though the text ends up readjusting and doesn't quite sit in the right spot, and it becomes hard to read: 
![image](https://user-images.githubusercontent.com/73264129/161817521-25e47ab4-091b-41ef-9f44-6d32c3f1bd17.png)

Also, can we move the download button over to the right a bit so that it aligns with the text above it? That will match the original design :)

Thanks,
Kristy

**Comment by linkfang** [comment]
Sounds good!

Please preview the updated version here:
https://deploy-preview-1448--jakartaee.netlify.app/release/9.1/

I added restriction to the new white paper box, so on large screens it won't go any further than here:
![image](https://user-images.githubusercontent.com/43075439/161836685-240d1755-5bcd-4689-bb00-e29a109529c0.png)

And actually, the blue text will show on top of the leaves on some other sizes. So, to make sure it will always be easy to read, I added a transparent white shadow for it. It will only be very obvious when it's on top of the leaves, like so:
![image](https://user-images.githubusercontent.com/43075439/161837162-005302ca-dfd1-47d2-ab01-ed4b13511175.png)
![image](https://user-images.githubusercontent.com/43075439/161837215-bb653820-4e62-4ede-8149-cd25703a8dd3.png)

**Comment by excentrickristy** [comment]
Looks good! Thank you :)

**Comment by linkfang** [comment]
NP! The change is now live!
