### ISSUE TITLE
Translation of the website pages and assets into Chinese

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1642]
We have translated the key website pages and assets identified by the Marketing Committee into Chinese and the translation is now ready.Here is the link to the drive:
https://drive.google.com/drive/u/0/folders/1hFyiRCXnNIgEQ0hcQzNw0wkT-f5W84ZH

Translations are divided into two folders: website and assets.

@laliwa  thank you so much for volunteering to lead the implementations on the website. Please let me and webdev team know if you need support anytime. thanks

**Comment by laliwa** [comment]
Hi, @shabnammayel 

Sorry to reply late, we will review all the materials by next Monday.
Till now, I can reply to my review of the Website part.
However, as you know, I have already translated some pages of the website before, and I found files on the Website are the same as those I had translated except for the following ones, maybe you can have confirmation with them, which part is their new translation.

# Website\data\zh\faq.zh.json
match the original translation but different in two places:
Eclipse Foundation as a brand, I left it be, and the agent translated the foundation into Chinese
"@type: "Answer"/"@type": "Question" It should be left as it is because it is a programming config key(maybe Chris can check this). 

# Website\data\zh\testimonials.zh.yml
some of the sentences are not translated well , maybe they should check again.
Hideki Nozaki "in order to continue its participation in the evolution of Java EE as Jakarta EE, providing it in the cloud native world"
Mark Little "The breadth of participation in combination with community governance"
Dmitri Cherkas "The seriousness, competence, and hospitality in the Jakarta EE community cannot be matched in any other community"
Lukas Jungmann "Eclipse open source is all about contributions and collaboration"

# Website\config.zh.toml
all "jp" in this file should be "zh"

**Comment by shabnammayel** [comment]
Hi @laliwa thanks for going through the translations to validate them. Here is the list of the items that the agency was tasked to get translated: https://docs.google.com/document/d/1wgBGnrhJob7_lddmhC4xDh_ufvfZbtuZiYx0DS0uadE/edit
These are the items that Marketing Committee requested to be translated. Most of these are Jakarta EE assets since as you mentioned many of the Jakarta EE pages are already translated by your team. However, since we gave them the links to the Markdown files, I think they also checked what pages were not translated and added them to the list. 

I will go through your suggested changes and ask them to incorporate and will also wait for more feedback from you regarding the translation of the assets.

**Comment by shabnammayel** [comment]
Please let me know if you think it's best to schedule a call to go through your feedback. thanks

**Comment by laliwa** [comment]
Thanks a lot Shabnam!

Here are all the assets reviewed by JKT China members https://drive.google.com/drive/folders/1V8no-hFeaRCervO_lnD6mEamsFQDOGAr?usp=sharing 

From our view, we see 3 things that may need to be improved during the agent translation

1\ we should check and estimate the completion date of the material, if the final translation is too far late than the original version, maybe the translation should be given up.

2\ some of the materials involved some tech terms and the agent cannot understand these, maybe these files should be translated by ones with a tech background.

3\ some of the translation has no meaning error, but are not suit for the Chinese expression, and should not be translated word by word, but need to translate with understanding.

**Comment by shabnammayel** [comment]
Thanks for the feedback Eric! What do you mean by the first one? do you mean how long it takes them to incorporate your feedback? because what is provided in the drive is their completed translations. but I can ask them to incorporate your feedback relatively quickly. maybe in a week or so. 
thanks again @laliwa

**Comment by shabnammayel** [comment]
@laliwa  qq are you good with the VoiceOver and video translations? I believe you already reviewed the scripts before they create the VoiceOver, right? 

Also can you please provide this email address the editing access so that they can ask questions in case they need some clarifications? lexcelera@gmail.com 

I see there are no comments in the community deck, does that one require any edits? thanks

**Comment by oliviergoulet5** [comment]
Is there anything left to do here @laliwa @shabnammayel? I was wondering if I could close this issue.

**Comment by shabnammayel** [comment]
@oliviergoulet5 I think we are good thanks
