### ISSUE TITLE
Please Publish Emily's blog on https://jakarta.ee/news

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#1678]
Here is Emily Jiang's blog, she submitted it using the newsroom but couldn't upload the images properly. She mentioned they keep getting lost. But we would like to have her blog on Jakarta's domain anyways. So kindly add the following content: 
[Developer Guide for Jakarta EE 10 and MP 6.0.docx](https://github.com/jakartaee/jakarta.ee/files/11491354/Developer.Guide.for.Jakarta.EE.10.and.MP.6.0.docx)

**Comment by Emily-Jiang** [comment]
Thank you @shabnammayel ! Here is the latest version of the blog.
[Developer Guide for Jakarta EE 10 and MP 6.0-latest.docx.zip](https://github.com/jakartaee/jakarta.ee/files/11492152/Developer.Guide.for.Jakarta.EE.10.and.MP.6.0-latest.docx.zip)

**Comment by oliviergoulet5** [comment]
Hi @Emily-Jiang and @shabnammayel, here is a preview of the blog post: 

https://deploy-preview-1681--jakartaee.netlify.app/news/developer-guide-for-jakarta-ee-10-and-microprofile-6.0/

Once approved, I'll deploy this page and it should appear on https://jakarta.ee/news/developer-guide-for-jakarta-ee-10-and-microprofile-6.0/. With that link you can submit it on the newsroom and all should be good!

**Comment by shabnammayel** [comment]
LGTM! @Emily-Jiang can you confirm so we can go live? thanks

**Comment by Emily-Jiang** [comment]
@oliviergoulet5 can you update the first 2 sentences with this:
On 22nd September 2022, [Jakarta EE 10](https://jakarta.ee/release/10/) was released. Three months later, [MicroProfile 6.0](https://microprofile.io/2023/01/10/microprofile-6-0-release/#) was released with [Jakarta EE 10 Core Profile](https://jakarta.ee/specifications/coreprofile/10/) alignment. 

Also, at the bottom of the page, can you use my Eclipse Account profile https://accounts.eclipse.org/users/ejiang instead of my github account?
Thanks! Thank you @shabnammayel for tagging me. For some reason, I missed the earlier notification. sorry about that!

**Comment by Emily-Jiang** [comment]
@oliviergoulet5 I add some suggested changes directly on your PR to cover all of my review comments. Only one more change for you to do is to update the author profile.

**Comment by oliviergoulet5** [comment]
Thanks. I'll look into updating it today.

**Comment by oliviergoulet5** [comment]
@Emily-Jiang I linked your Eclipse account to the blog post. Your image will still come from GitHub as there is no immediate way to get your Eclipse profile picture.

Blog posts hosted on jakarta.ee have only supported linking GitHub in the past. With the latest patch I would say linking an Eclipse account is partially supported. The profile image being the only thing missing. 

A feature request issue could be created for this functionality.
