### ISSUE TITLE
Modify videos page to read YouTube RSS Feed

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1731]
On this page: https://jakarta.ee/community/videos/

Our initial idea for this page is that it would update automatically when YouTube videos are posted. If I'm reading the code right, it looks like updating the page is a manual process at the moment.

Can we modify the video page to update automatically by reading the YouTube XML feed for each playlist?

Here is the XML feed for the Jakarta Tech Talk Playlist: https://www.youtube.com/feeds/videos.xml?playlist_id=PLutlXcN4EAwC64sgFLJSWAgQJvVo6T4Dh

We could associate a feed with each playlist we want to display in the dropdown.

**Comment by oliviergoulet5** [comment]
Neat. I always thought you could only do this via the YouTube API, but an XML feed makes it relatively easy.

I'll look into it

**Comment by shabnammayel** [comment]
@oliviergoulet5 is there any updates on this? thanks

**Comment by TanjaObradovic** [comment]
Thanks for raising attention to this issue @shabnammayel ... @oliviergoulet5 the page is so outdated  that the last video is from February 2, 2022

**Comment by oliviergoulet5** [comment]
Apologies for the late reply. I missed the notification for these replies.

We cannot fetch videos from the RSS feed because the YouTube servers are not configured to allow external domains such as jakarta.ee from fetching. Their cross-origin resource-sharing policy disallows it.

We do have an API for fetching YouTube playlists and videos... however, it won't work in this use-case. I go into detail here: https://github.com/jakartaee/jakarta.ee/issues/1848#issuecomment-1959960134

I can spend time in the upcoming week to add the missing videos to make this page up-to-date.

**Comment by oliviergoulet5** [comment]
We are looking into ways to automatically fetch a limited number of latest videos from a playlist. We'll most likely need to introduce a limit of videos fetched due to technical reasons. See https://gitlab.eclipse.org/eclipsefdn/it/api/eclipsefdn-media-link-api/-/issues/7.

If we add this capability to our API, we could make the videos page grab the latest 5 to 10 videos with a link to the full playlist. 

We would need to remove the pagination (the page numbers) from the bottom of the videos page since we wouldn't have enough videos for multiple pages.

WDYT @TanjaObradovic @excentrickristy @shabnammayel ?

We are still evaluating whether this is possible despite our technical constraints. We should still expect to get these video pages updated manually for the upcoming months.

**Comment by excentrickristy** [comment]
Hi @oliviergoulet5,
If we could display the latest 10 videos and have a link to the YouTube channel, I think that would be better than having to remember to manually update the page all the time. To me, it's better that the page always be the freshest content than have all of the content. We just might want to add something at the top of the page to introduce the fact that these are the latest 10 videos and to visit the YouTube channel for all of our videos. Once you have it functioning, I can provide some copy for you that reflects exactly what has been developed.

@shabnammayel @TanjaObradovic - do you agree?

**Comment by shabnammayel** [comment]
+1 @excentrickristy I also think it's best to have some latest videos than manually updating the whole content from time to time!

**Comment by oliviergoulet5** [comment]
@shabnammayel @excentrickristy Here is a preview with the updated videos: https://deploy-preview-1861--jakartaee.netlify.app/community/videos

It's using the descriptions from the YouTube videos themselves. They should be updated once the YouTube video description gets changed - however you'll need to let me know to redeploy the website. It cannot be updated in real time until we make it a feature on our API.

**Comment by excentrickristy** [comment]
This looks great @oliviergoulet5 - it pulls in a lot more videos than I was expecting so I think it's good to deploy!

**Comment by shabnammayel** [comment]
LGTM, too! thanks
