### ISSUE TITLE
Updating Learn Page to Include Videos and Spec Guides

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#1848]
Requesting on behalf of @shabnammayel 

Once the new specification guides are created (https://github.com/jakartaee/jakarta.ee/issues/1847) we would like to update the Learn Page to include the spec guides as well as a video feed.

Here is the design we are proposing for the Learn Page:
https://www.figma.com/file/lkN8FwRkbf4ZxaYQaeElot/Jakarta-Pages?type=design&node-id=58%3A2&mode=dev&t=OPiTMWPhED7u4Wve-1

The video feed style here matched the video page. It would be nice to have the videos pulled automatically from a playlist RSS feed as mentioned here: https://github.com/jakartaee/jakarta.ee/issues/1731

If that's possible, we will put together a playlist of the new specification videos.

**Comment by oliviergoulet5** [comment]
@excentrickristy Here is the progress on the learn page: https://deploy-preview-1857--jakartaee.netlify.app/learn/

Specifications are empty because no page exists yet. #1847 will need to go live before this patch.

The video section is still in progress. I need to add dates to our video list component from our component library. 

The video list component uses the Eclipse Media Link API, which handles fetching videos and playlists - however, it cannot retrieve a list of individual videos from a playlist. The webdev team has discussed it internally, but we ultimately chose not to do it due to technical reasons. Here is the feature request: https://gitlab.eclipse.org/eclipsefdn/it/api/eclipsefdn-media-link-api/-/issues/7. Now could also be the time to re-evaluate if it is something we want to support.

The RSS suggestion would not work because it's not integrated into our component yet. Still, more importantly, YouTube does not allow us to fetch from it due to its cross-origin resource-sharing policy. 

For now, I suggest we add the videos manually.

**Comment by excentrickristy** [comment]
@oliviergoulet5 the new page looks good!

Can you use this meta description: Learn how to use Jakarta EE, the open source platform for enterprise Java applications. Find tutorials, guides, documentation, and resources to get started.

@shabnammayel If we can't have a stream of the most recent videos, should we choose some videos to add manually or would you like to link to playlists instead like Olivier has setup? I think if we want to do playlists we will probably want to change the ones being represented on the page.

**Comment by shabnammayel** [comment]
We should add these two videos that are in the Specification Guides Playlist: https://www.youtube.com/watch?v=wK5Uis9QnFU&list=PLutlXcN4EAwDxs85DUnmbnWov3SusY9mG and https://www.youtube.com/watch?v=7mfVyPI360k&list=PLutlXcN4EAwDxs85DUnmbnWov3SusY9mG&index=2

**Comment by shabnammayel** [comment]
@oliviergoulet5 any progress with this page? thanks

**Comment by oliviergoulet5** [comment]
I haven't had the time to revisit this specific page. I moved my focus to other priority items, and writing the spec guides themselves. I'll post another update next week.

**Comment by oliviergoulet5** [comment]
Here is a preview @shabnammayel @excentrickristy https://deploy-preview-1857--jakartaee.netlify.app/learn/

**Comment by shabnammayel** [comment]
@oliviergoulet5 thanks, As I mentioned above, we only want these 3 specification videos displayed on the learn page: the Specification Guides Playlist: https://www.youtube.com/watch?v=wK5Uis9QnFU&list=PLutlXcN4EAwDxs85DUnmbnWov3SusY9mG and https://www.youtube.com/watch?v=7mfVyPI360k&list=PLutlXcN4EAwDxs85DUnmbnWov3SusY9mG&index=2

**Comment by oliviergoulet5** [comment]
@shabnammayel It will now only show videos from the specification guide playlist. There are only two videos right now, but it has a limit of 3.

**Comment by excentrickristy** [comment]
Page looks good to me!

**Comment by shabnammayel** [comment]
LGTM, too! Thanks @oliviergoulet5

**Comment by shabnammayel** [comment]
can this go live? @oliviergoulet5

**Comment by oliviergoulet5** [comment]
@shabnammayel The patch is still being reviewed. It will most likely go live tomorrow.

**Comment by oliviergoulet5** [comment]
Going live @shabnammayel
