### ISSUE TITLE
Bad license format

### ISSUE THREAD

**Issue by hendrikebbers** [jakartaee/jakarta.ee#2035]
Most repositories of JakartaEE store the EPL license in a markdown file (example: https://github.com/jakartaee/jsonp-api).
By doing so GitHub understands that a license is present but can not interpret it. Based on that the license name is not shown in the GitHub ui and the GitHub API returns "OTHER" for the license.

```
"license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
```
<img width="1426" alt="Bildschirmfoto 2024-11-07 um 09 45 15" src="https://github.com/user-attachments/assets/b0f3f3a0-659d-43fb-b817-847085d37768">

By switching the license file to plain text GitHub will understand it, show EPL directly in the UI and provides all metadata by the REST API:

<img width="1271" alt="Bildschirmfoto 2024-11-07 um 09 50 25" src="https://github.com/user-attachments/assets/3011e652-f7a8-41c9-a75a-32a212a2c6dd">

```
{
  "key": "epl-2.0",
  "name": "Eclipse Public License 2.0",
  "spdx_id": "EPL-2.0",
  "url": "https://api.github.com/licenses/epl-2.0",
  "node_id": "MDc6TGljZW5zZTMy",
  ...
}
```

A sample can be found at https://github.com/hendrikebbers/jsonp-api

I will be happy to help here and refactor the license files in a better format if you give me the go :)

**Comment by oliviergoulet5** [comment]
Hi @hendrikebbers,

I'm unsure whether this is the best place to create this issue. This is the repo for the Jakarta EE website. 

Perhaps @TanjaObradovic can help you communicate your request to the Jakarta EE repos?

**Comment by hendrikebbers** [comment]
@TanjaObradovic @ivargrimstad what is the best place for such issue and can you transfer it?

**Comment by ivargrimstad** [comment]
> @TanjaObradovic @ivargrimstad what is the best place for such issue and can you transfer it?

This is probably not an isolated Jakarta EE issue. Most likely affecting all Eclipse Foundation projects. I think we probably should create a GitLab issue for someone in the EMO or Webdev to look at.

**Comment by hendrikebbers** [comment]
@waynebeaton might the the best person in that case, right?

**Comment by waynebeaton** [comment]
AFAICT, it's not the markdown formatting that's the problem. Rather, the problem is that the license file contains three different texts. GitHub correctly understands that the license is _complex_.

An important detail here is that the Jakarta JSON-P project uses the EPL-2.0 _with a secondary licence_. Stating the licence as "EPL-2.0" isn't correct. 

In SPDX terms, the licence expression is `EPL-2.0 or GPL-2.0-only with Classpath-Exception-2.0`.

I'm not aware of a means by which we can make GitHub accurately reflect a licence expression.

If you want to pursue this more broadly, open an help desk issue and we'll figure out where to move it.
