### ISSUE TITLE
Creating a "GitHub Issue" template for those who want to get listed on the Compatible Product page

### ISSUE THREAD

**Issue by shabnammayel** [jakartaee/jakarta.ee#379]
**Is your feature request related to a problem? Please describe.**
We would need a "GitHub Issue" template to include it in the "Get Listed" page.
Stephanie is working on creating a mock up for "Compatible Product" page and "Get Listed" page for jakarta.ee/compatibility

**Describe the solution you'd like**
In the "Get Listed" page we will need to have a link that directs people to a "GitHub Issue" template that includes the following copy for them to fill in:

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

A corporate email address to confirm that you are an authorized representative of the company whose product information you are submitting,
A product name and version,
A product logo (optional)
The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product,
The URL to the published public TCK test results demonstrating compatibility as defined in the TCK Process,
The URL where Compatible Software Product is available for download

**Comment by chrisguindon** [comment]
@shabnammayel Are you requesting that we update the existing one: https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md

**Comment by shabnammayel** [comment]
@chrisguindon yes, sure we can update the content on the existing one. thanks

**Comment by autumnfound** [comment]
@shabnammayel it looks like the template already encompasses most of what you're looking for. I've included the template below this text for comparison:

For Compatible Software Products to be listed on the Jakarta EE official list of Software Products must provide, as a minimum:

**A product name and version**

**A product logo (optional)**

**The Participant, Enterprise or Strategic Member name supporting the Compatible Software Product**

**The URL to the published public TCK test results demonstrating compatibility as defined in the TCK Process**

**The URL where Compatible Software Product is available for download**

---
The stylistic differences are mainly to emphasize what is part of the template vs user entered information (bold vs normal font weight). Otherwise, it looks like you've modified the foreword, and added a request to include a corporate email. Should I just add the new field in the given format, and modify the foreword?

**Comment by shabnammayel** [comment]
@autumnfound Yes, the first sentence needs to be changed to: 

To include your Compatible Software Product on the Jakarta EE official list of Compatible Software Products, please provide the following information:

and also the following item needs to be added before asking for "A product name and version": 

A corporate email address to confirm that you are an authorized representative of the company whose product information you are submitting,

**Comment by autumnfound** [comment]
@shabnammayel please check the link provided by @chrisguindon in a previous comments, as the changes are now live.

> @shabnammayel Are you requesting that we update the existing one: https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md

**Comment by shabnammayel** [comment]
Looks great @autumnfound thanks
