### ISSUE TITLE
Explain current situation of specs and link JCP

### ISSUE THREAD

**Issue by ggam** [jakartaee/jakarta.ee#465]
**Is your feature request related to a problem? Please describe.**
From the mailing list: https://www.eclipse.org/lists/jakarta.ee-community/msg01237.html

Users don't understand why the specs are  just placeholders and how a blank document can be equivalent to the Java EE 8.

Users need an explanation of the current status of the process and specs donation.

**Describe the solution you'd like**
As proposed on the mailing list: https://www.eclipse.org/lists/jakarta.ee-community/msg01254.html

We can add some warning on the placeholder specs, explaining the reasons for it, linking to the real spec on the JCP site, and a page with enough information to understand what to expect and why it's safe to assume Jakarta EE 8 is 100% compatible to Java EE 8.

**Comment by TanjaObradovic** [comment]
Please correct me if I am wrong, but we explained this in various blogs and press releases
(just as an example https://blogs.eclipse.org/post/tanja-obradovic/jcp-copyright-licensing-request), but we failed to update the issue here.
At this point I believe we can close this issue. Please let me know if i am correct. Thanks!

**Comment by TanjaObradovic** [comment]
Closing as I believe this has been addressed.
