### ISSUE TITLE
Add event: JakartaOne in Spanish

### ISSUE THREAD

**Issue by shanda-eclipse** [jakartaee/jakarta.ee#831]
Title: JakartaOne in Spanish

Date: Monday, October 12, 2020 - 08:00 to 17:00

Location: Virtual Event

Website: https://jakartaone.org/2020/hispano/

**Comment by aeiras** [comment]
Hey @shanda-eclipse, you need to use the JakartaONE dedicate repo for above issue to enable proper tracing! 

Cheers

**Comment by autumnfound** [comment]
@aeiras I believe Shanda was asking for the event to be added to the internal list to be displayed on the site, rather than a new event! We've just migrated over today to using a central source for news and events for this site, so we should see that up soon without having to update the site. 

@shanda-eclipse Chris just merged in a change to use the newsroom content on this site. I just checked and this event is now included! I'll close this issue since Jakarta EE news and events are managed through the newsroom site :)
